### ISSUE TITLE
EA

### ISSUE THREAD

**Issue by guiimarques18** [RodrigoAguiar0/TACS-ES-2020-2-RaroListaDeFilmes#2]
É possível especificar com mais detalhes a arquitetura, em: https://github.com/RodrigoAguiar0/TACS-ES-2020-2-RaroListaDeFilmes/blob/main/Design/EA/Vis%C3%A3o%20Geral%20Arquitetural.png

Especificar quais são os acessos ao Banco de Dados, qual BD, por exemplo.

**Comment by RodrigoAguiar0** [comment]
Foi inserido um documento específico de decisão sobre banco de dados na atividade de hoje. Atende às necessidades de mudanças no documento de arquitetura?

**Comment by guiimarques18** [comment]
Sim!
